### ISSUE TITLE
[QIP][DAITO]SSE Enabled bucket creation does not honor SSE

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#292] opened 2020-01-30 14:23 UTC
Create Bucket with SSE Enabled 
Bucket list shows Encryption No
Same in DB
![image](https://user-images.githubusercontent.com/48085413/73457702-184dd500-439a-11ea-8931-2ecbef76d751.png)
| awsencbkt1aks | 94b280022d0c4401bcf3b0ea85870519 | 558057c4256545bd8a307c37464003c9 | 2020-01-30 19:50:07 |      0 | aws_bknd   |       0 |    1 | {"cannedAcl": "private"} | null | null                                                                                                                                                                                                     | ""     | Disabled   | null        | 2020-01-30 14:20:07 |
+---------------+----------------------------------+----------------------------------+---------------------+--------+------------+---------+------+--------------------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+-------------+---------------------+
![image](https://user-images.githubusercontent.com/48085413/73457752-2c91d200-439a-11ea-85a6-dac647d2e8a6.png)

**Comment by anvithks** [comment] 2020-01-31 03:36
@kumarashit could you share the screenshot / response for the list buckets API call.  
If the response has Encryption enabled and the dashboard is not displaying it then it is a dashboard issue. But if SSE is not enabled in the  response  then we will have to check the backend.

**Comment by anvithks** [comment] 2020-01-31 08:24
@kumarashit As discussed and after checking the output on the system it seems there is some issue in the response. @rhsakarpos Please check the issue. @kumarashit Please share the screenshot of the response for the Encryption API call.

**Comment by anvithks** [comment] 2020-05-03 18:48
Closing since this is an issue with the backend and could not be reproduced.

**Comment by kumarashit** [comment] 2020-05-04 18:06
@anvithks as this is an issue with the backend, please move this to multi-cloud or open another issue in multi-cloud and then close this with reference for tracking. Thanks

**Comment by anvithks** [comment] 2020-06-17 06:25
Raised the issue in [Multi-cloud repository Issue #1012](https://github.com/sodafoundation/multi-cloud/issues/1012). Closing here.

**Closed by anvithks** 2020-06-17 06:25 UTC
