### ISSUE TITLE
OpenSDS dashboard sends Download successful message on cancelling the download

### ISSUE THREAD

**Issue by nguptaopensds** [sodafoundation/dashboard#293] opened 2020-01-31 11:33 UTC
1. Click on Download tab in objects
2. On the browse window which pops up after that, hit cancel
3. The "Download successfully" message comes up.

![image](https://user-images.githubusercontent.com/48784300/73536201-77b7ed80-444b-11ea-89c1-29240b7bf81c.png)

**Comment by anvithks** [comment] 2020-05-03 18:45
Duplicate of #286

**Comment by anvithks** [comment] 2020-06-17 06:26
Closing this as duplicate.

**Closed by anvithks** 2020-06-17 06:26 UTC
Labels: duplicate
